/* Generated By:JJTree: Do not edit this line. PGN_TagPair.java */

package chess.parser.pgn;

/* Generated By:JJTree: Do not edit this line. PGN_TagPair.java */

public class PGN_TagPair extends SimpleNode {

  String name;
  String value;

  public PGN_TagPair(int id) {
	super(id);
  }  

  public PGN_TagPair(PGN p, int id) {
	super(p, id);
  }  

  public String toString()
  {
	StringBuffer buf = new StringBuffer();
	buf.append(name).append(" = ");
	buf.append(value);
	return buf.toString();
  }  

  public void setName(Token t)
  {
	name = t.image;
  }  

  public void setValue(Token t)
  {
	// remove quotes
	value = t.image.substring(1, t.image.length()-1);
  }  

  public String getName() {return name;}    public String getValue() {return value;}  }