/* Generated By:JJTree: Do not edit this line. PGN_Game.java */

package chess.parser.pgn;

/* Generated By:JJTree: Do not edit this line. PGN_Game.java */

public class PGN_Game extends SimpleNode {

  public final static int RESULT_UNKNOWN    = 0;
  public final static int RESULT_WHITE_WINS = 1;
  public final static int RESULT_BLACK_WINS = 2;
  public final static int RESULT_DRAW       = 3;

  protected int result = RESULT_UNKNOWN;

  public PGN_Game(int id) {
	super(id);
  }  

  public PGN_Game(PGN p, int id) {
	super(p, id);
  }  

  public void setResult(Token t)
  {
	if (t == null)
	{
	  result = RESULT_UNKNOWN;
	}
	else
	{
	  String r = t.image;

	  if (r.equals("1-0"))
		result = RESULT_WHITE_WINS;
	  else if (r.equals("0-1"))
		result = RESULT_BLACK_WINS;
	  else if (r.equals("1/2-1/2"))
		result = RESULT_DRAW;
	  else
		result = RESULT_UNKNOWN;
	}
  }  
}