/* Generated By:JJTree: Do not edit this line. PGN_Start.java */

package chess.parser.pgn;

/* Generated By:JJTree: Do not edit this line. PGN_Start.java */

public class PGN_Start extends SimpleNode {
  public PGN_Start(int id) {
	super(id);
  }  

  public PGN_Start(PGN p, int id) {
	super(p, id);
  }  

}