/* Generated By:JJTree: Do not edit this line. PGN_Castle.java */

package chess.parser.pgn;

/* Generated By:JJTree: Do not edit this line. PGN_Castle.java */

public class PGN_Castle extends PGN_MoveDesc {
  public PGN_Castle(int id) {
	super(id);
  }  

  public PGN_Castle(PGN p, int id) {
	super(p, id);
  }  

}