/* Generated By:JJTree&JavaCC: Do not edit this line. PGNConstants.java */
package chess.parser.pgn;

/* Generated By:JJTree&JavaCC: Do not edit this line. PGNConstants.java */
public interface PGNConstants {

  int EOF = 0;
  int FILE = 1;
  int PIECE_TYPE = 2;
  int L_BRACKET = 3;
  int KINGSIDE_CASTLE = 4;
  int QUEENSIDE_CASTLE = 5;
  int DIGIT = 6;
  int DOT = 7;
  int NAG = 8;
  int GAME_RESULT = 9;
  int WIN_WHITE = 10;
  int WIN_BLACK = 11;
  int DRAW = 12;
  int UNKNOWN = 13;
  int QUOTES = 14;
  int TAG_NAME = 15;
  int QUOTED_STRING = 16;
  int INTAG_WHITESPACE = 17;
  int R_BRACKET = 18;
  int DEF_WHITESPACE = 19;
  int L_BRACE = 20;
  int L_PARANTHESIS = 21;
  int COMMENT_BRACE_TEXT = 22;
  int R_BRACE = 23;
  int COMMENT_PARAN_TEXT = 24;
  int R_PARANTHESIS = 25;
  int RANK = 26;
  int CAPTURE = 27;
  int EQUALS = 28;
  int PROMOTION_TYPE = 29;
  int ANNOTATIONS = 30;
  int CHECK = 31;
  int CHECKMATE = 32;
  int MOVESPACE = 33;

  int inMove = 0;
  int comment_paran = 1;
  int comment_brace = 2;
  int WithinTagPair = 3;
  int DEFAULT = 4;

  String[] tokenImage = {
	"<EOF>",
	"<FILE>",
	"<PIECE_TYPE>",
	"\"[\"",
	"<KINGSIDE_CASTLE>",
	"<QUEENSIDE_CASTLE>",
	"<DIGIT>",
	"\".\"",
	"<NAG>",
	"<GAME_RESULT>",
	"\"1-0\"",
	"\"0-1\"",
	"\"1/2-1/2\"",
	"\"*\"",
	"\"\\\"\"",
	"<TAG_NAME>",
	"<QUOTED_STRING>",
	"<INTAG_WHITESPACE>",
	"\"]\"",
	"<DEF_WHITESPACE>",
	"\"{\"",
	"\"(\"",
	"<COMMENT_BRACE_TEXT>",
	"\"}\"",
	"<COMMENT_PARAN_TEXT>",
	"\")\"",
	"<RANK>",
	"\"x\"",
	"\"=\"",
	"<PROMOTION_TYPE>",
	"<ANNOTATIONS>",
	"\"+\"",
	"<CHECKMATE>",
	"<MOVESPACE>",
  };



}