/* Generated By:JJTree: Do not edit this line. PGNTreeConstants.java */

package chess.parser.pgn;

/* Generated By:JJTree: Do not edit this line. PGNTreeConstants.java */

public interface PGNTreeConstants
{
  public int JJTSTART = 0;
  public int JJTGAME = 1;
  public int JJTTAGPAIR = 2;
  public int JJTVOID = 3;
  public int JJTCASTLE = 4;
  public int JJTMOVEDESC = 5;


  public String[] jjtNodeName = {
	"Start",
	"Game",
	"TagPair",
	"void",
	"Castle",
	"MoveDesc",
  };

}